org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=256m -Dfile.encoding=UTF-8
org.gradle.daemon-max-heap-size=1024m
kotlin.daemon.jvmargs=-Xmx768m
kotlin.daemon.enable=false
android.d8.maxHeapSize=512m
android.suppressUnsupportedCompileSdk=36
org.gradle.parallel=true
org.gradle.caching=true
#org.gradle.configuration-cache=true

android.useAndroidX=true
android.nonTransitiveRClass=true
android.aapt2FromMavenOverride=C\:\\Users\\aryan chavan\\AppData\\Local\\Android\\Sdk\\build-tools\\35.0.0\\aapt2.exe

kotlin.code.style=official

kotlin.incremental=true

ksp.incremental=true
